title: Nicholas' Website
description: A virtual discription of a website to house random thoughts and builds

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Academic Projects:
#   - Directory: "school"
    - Python Plot: "python-plot"
    - Assembly: "assembly"


avatar: "/assets/img/me-avatar.jpg"
round-avatar: true

social-network-links:
  email: "nick0207022@gmail.com"
  facebook: nicholas.tang.3139
  github: tangnicholas
#  twitter: daattali
  rss: false
  linkedin: nicholas-tang-702b38145
  instagram: tang.nicholas
#  youtube: user/deanat78
#  spotify: yourname
  telephone: +17783193601

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: true
  linkedin: true
  instagram: true
  email: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "tangnicholas.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
